//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opp", Namespace="http://schemas.datacontract.org/2004/07/CrmService")]
    public partial class Opp : object
    {
        
        private string aciklamaField;
        
        private string adsetField;
        
        private bool altibirField;
        
        private string anketaileField;
        
        private string anketbutceField;
        
        private string anketevcilhayvanField;
        
        private string anketgayrimenkultipField;
        
        private string anketkitaField;
        
        private string anketortamField;
        
        private string aramaizinField;
        
        private bool besbirField;
        
        private bool birbirField;
        
        private string browserlangField;
        
        private int ceretapField;
        
        private string cihazturuField;
        
        private bool dortbirField;
        
        private string emailField;
        
        private string emailizinField;
        
        private string firstnameField;
        
        private string formField;
        
        private string formlinkField;
        
        private string formtipiField;
        
        private string gayrimenkultipiField;
        
        private bool gdprapprovalField;
        
        private string gdprurlField;
        
        private string googleIDField;
        
        private bool ikibirField;
        
        private string ilgilendigiprojeField;
        
        private System.DateTime kayittarihiField;
        
        private string kurumsalsatiskampanyaField;
        
        private string lastnameField;
        
        private string milliyetField;
        
        private string mobileField;
        
        private string otpField;
        
        private string passwordField;
        
        private string projectnameField;
        
        private string referrerField;
        
        private string smsizinField;
        
        private string tokenField;
        
        private bool ucbirField;
        
        private string ulkeField;
        
        private string usernameField;
        
        private string utmcampaignField;
        
        private string utmcontentField;
        
        private string utmmediumField;
        
        private string utmsourceField;
        
        private string utmtermField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adset
        {
            get
            {
                return this.adsetField;
            }
            set
            {
                this.adsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool altibir
        {
            get
            {
                return this.altibirField;
            }
            set
            {
                this.altibirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketaile
        {
            get
            {
                return this.anketaileField;
            }
            set
            {
                this.anketaileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketbutce
        {
            get
            {
                return this.anketbutceField;
            }
            set
            {
                this.anketbutceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketevcilhayvan
        {
            get
            {
                return this.anketevcilhayvanField;
            }
            set
            {
                this.anketevcilhayvanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketgayrimenkultip
        {
            get
            {
                return this.anketgayrimenkultipField;
            }
            set
            {
                this.anketgayrimenkultipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketkita
        {
            get
            {
                return this.anketkitaField;
            }
            set
            {
                this.anketkitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anketortam
        {
            get
            {
                return this.anketortamField;
            }
            set
            {
                this.anketortamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aramaizin
        {
            get
            {
                return this.aramaizinField;
            }
            set
            {
                this.aramaizinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool besbir
        {
            get
            {
                return this.besbirField;
            }
            set
            {
                this.besbirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool birbir
        {
            get
            {
                return this.birbirField;
            }
            set
            {
                this.birbirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string browserlang
        {
            get
            {
                return this.browserlangField;
            }
            set
            {
                this.browserlangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ceretap
        {
            get
            {
                return this.ceretapField;
            }
            set
            {
                this.ceretapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cihazturu
        {
            get
            {
                return this.cihazturuField;
            }
            set
            {
                this.cihazturuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool dortbir
        {
            get
            {
                return this.dortbirField;
            }
            set
            {
                this.dortbirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailizin
        {
            get
            {
                return this.emailizinField;
            }
            set
            {
                this.emailizinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formlink
        {
            get
            {
                return this.formlinkField;
            }
            set
            {
                this.formlinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formtipi
        {
            get
            {
                return this.formtipiField;
            }
            set
            {
                this.formtipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gayrimenkultipi
        {
            get
            {
                return this.gayrimenkultipiField;
            }
            set
            {
                this.gayrimenkultipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool gdprapproval
        {
            get
            {
                return this.gdprapprovalField;
            }
            set
            {
                this.gdprapprovalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gdprurl
        {
            get
            {
                return this.gdprurlField;
            }
            set
            {
                this.gdprurlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string googleID
        {
            get
            {
                return this.googleIDField;
            }
            set
            {
                this.googleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ikibir
        {
            get
            {
                return this.ikibirField;
            }
            set
            {
                this.ikibirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ilgilendigiproje
        {
            get
            {
                return this.ilgilendigiprojeField;
            }
            set
            {
                this.ilgilendigiprojeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime kayittarihi
        {
            get
            {
                return this.kayittarihiField;
            }
            set
            {
                this.kayittarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kurumsalsatiskampanya
        {
            get
            {
                return this.kurumsalsatiskampanyaField;
            }
            set
            {
                this.kurumsalsatiskampanyaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string milliyet
        {
            get
            {
                return this.milliyetField;
            }
            set
            {
                this.milliyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string otp
        {
            get
            {
                return this.otpField;
            }
            set
            {
                this.otpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string projectname
        {
            get
            {
                return this.projectnameField;
            }
            set
            {
                this.projectnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referrer
        {
            get
            {
                return this.referrerField;
            }
            set
            {
                this.referrerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string smsizin
        {
            get
            {
                return this.smsizinField;
            }
            set
            {
                this.smsizinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ucbir
        {
            get
            {
                return this.ucbirField;
            }
            set
            {
                this.ucbirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ulke
        {
            get
            {
                return this.ulkeField;
            }
            set
            {
                this.ulkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmcampaign
        {
            get
            {
                return this.utmcampaignField;
            }
            set
            {
                this.utmcampaignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmcontent
        {
            get
            {
                return this.utmcontentField;
            }
            set
            {
                this.utmcontentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmmedium
        {
            get
            {
                return this.utmmediumField;
            }
            set
            {
                this.utmmediumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmsource
        {
            get
            {
                return this.utmsourceField;
            }
            set
            {
                this.utmsourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmterm
        {
            get
            {
                return this.utmtermField;
            }
            set
            {
                this.utmtermField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/DAL.Entities")]
    public partial class Login : object
    {
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Incident", Namespace="http://schemas.datacontract.org/2004/07/DAL.Entities")]
    public partial class Incident : object
    {
        
        private bool ActivitiesCompleteField;
        
        private int ActualServiceUnitsField;
        
        private int BilledServiceUnitsField;
        
        private bool BlockedProfileField;
        
        private int CaseOriginCodeField;
        
        private int CaseTypeCodeField;
        
        private bool CheckEmailField;
        
        private System.Guid ContractDetailIdField;
        
        private System.Guid ContractIdField;
        
        private int ContractServiceLevelCodeField;
        
        private System.Guid CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private System.Guid CreatedOnBehalfByField;
        
        private bool CustomerContactedField;
        
        private System.Guid CustomerIdField;
        
        private string CustomerIdNameField;
        
        private int CustomerIdTypeField;
        
        private string CustomerIdYomiNameField;
        
        private int CustomerSatisfactionCodeField;
        
        private string DescriptionField;
        
        private System.Guid EntitlementIdField;
        
        private System.Guid EntityImageIdField;
        
        private System.DateTime EscalatedOnField;
        
        private decimal ExchangeRateField;
        
        private System.Guid ExistingCaseField;
        
        private System.Guid FirstResponseByKPIIdField;
        
        private int FirstResponseSLAStatusField;
        
        private bool FirstResponseSentField;
        
        private bool FollowUpTaskCreatedField;
        
        private System.DateTime FollowupByField;
        
        private int ImportSequenceNumberField;
        
        private System.Guid IncidentIdField;
        
        private int IncidentStageCodeField;
        
        private float InfluenceScoreField;
        
        private bool IsEscalatedField;
        
        private System.Guid KbArticleIdField;
        
        private System.DateTime LastOnHoldTimeField;
        
        private System.Guid MasterIdField;
        
        private bool MergedField;
        
        private int MessageTypeCodeField;
        
        private System.Guid ModifiedByField;
        
        private System.DateTime ModifiedOnField;
        
        private System.Guid ModifiedOnBehalfByField;
        
        private int OnHoldTimeField;
        
        private System.DateTime OverriddenCreatedOnField;
        
        private System.Guid OwnerIdField;
        
        private int OwnerIdTypeField;
        
        private System.Guid OwningBusinessUnitField;
        
        private System.Guid ParentCaseIdField;
        
        private System.Guid PrimaryContactIdField;
        
        private int PriorityCodeField;
        
        private System.Guid ProcessIdField;
        
        private System.Guid ProductIdField;
        
        private string ProductSerialNumberField;
        
        private System.Guid ProjectIdField;
        
        private System.DateTime ResolveByField;
        
        private System.Guid ResolveByKPIIdField;
        
        private int ResolveBySLAStatusField;
        
        private System.DateTime ResponseByField;
        
        private System.Guid ResponsibleContactIdField;
        
        private bool RouteCaseField;
        
        private System.Guid SLAInvokedIdField;
        
        private float SentimentValueField;
        
        private int ServiceStageField;
        
        private int SeverityCodeField;
        
        private System.Guid SocialProfileIdField;
        
        private System.Guid StageIdField;
        
        private int StateCodeField;
        
        private int StatusCodeField;
        
        private System.Guid SubjectIdField;
        
        private string TicketNumberField;
        
        private int TimeZoneRuleVersionNumberField;
        
        private string TitleField;
        
        private System.Guid TransactionCurrencyIdField;
        
        private string TraversedPathField;
        
        private int UTCConversionTimeZoneCodeField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobileField;
        
        private string projectNameField;
        
        private string utmSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActivitiesComplete
        {
            get
            {
                return this.ActivitiesCompleteField;
            }
            set
            {
                this.ActivitiesCompleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActualServiceUnits
        {
            get
            {
                return this.ActualServiceUnitsField;
            }
            set
            {
                this.ActualServiceUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BilledServiceUnits
        {
            get
            {
                return this.BilledServiceUnitsField;
            }
            set
            {
                this.BilledServiceUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BlockedProfile
        {
            get
            {
                return this.BlockedProfileField;
            }
            set
            {
                this.BlockedProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseOriginCode
        {
            get
            {
                return this.CaseOriginCodeField;
            }
            set
            {
                this.CaseOriginCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseTypeCode
        {
            get
            {
                return this.CaseTypeCodeField;
            }
            set
            {
                this.CaseTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckEmail
        {
            get
            {
                return this.CheckEmailField;
            }
            set
            {
                this.CheckEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContractDetailId
        {
            get
            {
                return this.ContractDetailIdField;
            }
            set
            {
                this.ContractDetailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContractId
        {
            get
            {
                return this.ContractIdField;
            }
            set
            {
                this.ContractIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContractServiceLevelCode
        {
            get
            {
                return this.ContractServiceLevelCodeField;
            }
            set
            {
                this.ContractServiceLevelCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedOnBehalfBy
        {
            get
            {
                return this.CreatedOnBehalfByField;
            }
            set
            {
                this.CreatedOnBehalfByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CustomerContacted
        {
            get
            {
                return this.CustomerContactedField;
            }
            set
            {
                this.CustomerContactedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerIdName
        {
            get
            {
                return this.CustomerIdNameField;
            }
            set
            {
                this.CustomerIdNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerIdType
        {
            get
            {
                return this.CustomerIdTypeField;
            }
            set
            {
                this.CustomerIdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerIdYomiName
        {
            get
            {
                return this.CustomerIdYomiNameField;
            }
            set
            {
                this.CustomerIdYomiNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerSatisfactionCode
        {
            get
            {
                return this.CustomerSatisfactionCodeField;
            }
            set
            {
                this.CustomerSatisfactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EntitlementId
        {
            get
            {
                return this.EntitlementIdField;
            }
            set
            {
                this.EntitlementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EntityImageId
        {
            get
            {
                return this.EntityImageIdField;
            }
            set
            {
                this.EntityImageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EscalatedOn
        {
            get
            {
                return this.EscalatedOnField;
            }
            set
            {
                this.EscalatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate
        {
            get
            {
                return this.ExchangeRateField;
            }
            set
            {
                this.ExchangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExistingCase
        {
            get
            {
                return this.ExistingCaseField;
            }
            set
            {
                this.ExistingCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FirstResponseByKPIId
        {
            get
            {
                return this.FirstResponseByKPIIdField;
            }
            set
            {
                this.FirstResponseByKPIIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstResponseSLAStatus
        {
            get
            {
                return this.FirstResponseSLAStatusField;
            }
            set
            {
                this.FirstResponseSLAStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FirstResponseSent
        {
            get
            {
                return this.FirstResponseSentField;
            }
            set
            {
                this.FirstResponseSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FollowUpTaskCreated
        {
            get
            {
                return this.FollowUpTaskCreatedField;
            }
            set
            {
                this.FollowUpTaskCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FollowupBy
        {
            get
            {
                return this.FollowupByField;
            }
            set
            {
                this.FollowupByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportSequenceNumber
        {
            get
            {
                return this.ImportSequenceNumberField;
            }
            set
            {
                this.ImportSequenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IncidentId
        {
            get
            {
                return this.IncidentIdField;
            }
            set
            {
                this.IncidentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentStageCode
        {
            get
            {
                return this.IncidentStageCodeField;
            }
            set
            {
                this.IncidentStageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float InfluenceScore
        {
            get
            {
                return this.InfluenceScoreField;
            }
            set
            {
                this.InfluenceScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEscalated
        {
            get
            {
                return this.IsEscalatedField;
            }
            set
            {
                this.IsEscalatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid KbArticleId
        {
            get
            {
                return this.KbArticleIdField;
            }
            set
            {
                this.KbArticleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastOnHoldTime
        {
            get
            {
                return this.LastOnHoldTimeField;
            }
            set
            {
                this.LastOnHoldTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MasterId
        {
            get
            {
                return this.MasterIdField;
            }
            set
            {
                this.MasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Merged
        {
            get
            {
                return this.MergedField;
            }
            set
            {
                this.MergedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageTypeCode
        {
            get
            {
                return this.MessageTypeCodeField;
            }
            set
            {
                this.MessageTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ModifiedOnBehalfBy
        {
            get
            {
                return this.ModifiedOnBehalfByField;
            }
            set
            {
                this.ModifiedOnBehalfByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnHoldTime
        {
            get
            {
                return this.OnHoldTimeField;
            }
            set
            {
                this.OnHoldTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OverriddenCreatedOn
        {
            get
            {
                return this.OverriddenCreatedOnField;
            }
            set
            {
                this.OverriddenCreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerIdType
        {
            get
            {
                return this.OwnerIdTypeField;
            }
            set
            {
                this.OwnerIdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OwningBusinessUnit
        {
            get
            {
                return this.OwningBusinessUnitField;
            }
            set
            {
                this.OwningBusinessUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentCaseId
        {
            get
            {
                return this.ParentCaseIdField;
            }
            set
            {
                this.ParentCaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PrimaryContactId
        {
            get
            {
                return this.PrimaryContactIdField;
            }
            set
            {
                this.PrimaryContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriorityCode
        {
            get
            {
                return this.PriorityCodeField;
            }
            set
            {
                this.PriorityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProcessId
        {
            get
            {
                return this.ProcessIdField;
            }
            set
            {
                this.ProcessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSerialNumber
        {
            get
            {
                return this.ProductSerialNumberField;
            }
            set
            {
                this.ProductSerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResolveBy
        {
            get
            {
                return this.ResolveByField;
            }
            set
            {
                this.ResolveByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResolveByKPIId
        {
            get
            {
                return this.ResolveByKPIIdField;
            }
            set
            {
                this.ResolveByKPIIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResolveBySLAStatus
        {
            get
            {
                return this.ResolveBySLAStatusField;
            }
            set
            {
                this.ResolveBySLAStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseBy
        {
            get
            {
                return this.ResponseByField;
            }
            set
            {
                this.ResponseByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResponsibleContactId
        {
            get
            {
                return this.ResponsibleContactIdField;
            }
            set
            {
                this.ResponsibleContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RouteCase
        {
            get
            {
                return this.RouteCaseField;
            }
            set
            {
                this.RouteCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SLAInvokedId
        {
            get
            {
                return this.SLAInvokedIdField;
            }
            set
            {
                this.SLAInvokedIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float SentimentValue
        {
            get
            {
                return this.SentimentValueField;
            }
            set
            {
                this.SentimentValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceStage
        {
            get
            {
                return this.ServiceStageField;
            }
            set
            {
                this.ServiceStageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SocialProfileId
        {
            get
            {
                return this.SocialProfileIdField;
            }
            set
            {
                this.SocialProfileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateCode
        {
            get
            {
                return this.StateCodeField;
            }
            set
            {
                this.StateCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SubjectId
        {
            get
            {
                return this.SubjectIdField;
            }
            set
            {
                this.SubjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketNumber
        {
            get
            {
                return this.TicketNumberField;
            }
            set
            {
                this.TicketNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeZoneRuleVersionNumber
        {
            get
            {
                return this.TimeZoneRuleVersionNumberField;
            }
            set
            {
                this.TimeZoneRuleVersionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransactionCurrencyId
        {
            get
            {
                return this.TransactionCurrencyIdField;
            }
            set
            {
                this.TransactionCurrencyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraversedPath
        {
            get
            {
                return this.TraversedPathField;
            }
            set
            {
                this.TraversedPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UTCConversionTimeZoneCode
        {
            get
            {
                return this.UTCConversionTimeZoneCodeField;
            }
            set
            {
                this.UTCConversionTimeZoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string projectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string utmSource
        {
            get
            {
                return this.utmSourceField;
            }
            set
            {
                this.utmSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SResult", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WS.Login))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WS.Incident))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WS.Opp))]
    public partial class SResult : object
    {
        
        private object DataField;
        
        private string MessageField;
        
        private bool ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.ICrmService")]
    public interface ICrmService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/malsahibisilme", ReplyAction="http://tempuri.org/ICrmService/malsahibisilmeResponse")]
        System.Threading.Tasks.Task malsahibisilmeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/VIPOnayMail", ReplyAction="http://tempuri.org/ICrmService/VIPOnayMailResponse")]
        System.Threading.Tasks.Task VIPOnayMailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GecikmeMail", ReplyAction="http://tempuri.org/ICrmService/GecikmeMailResponse")]
        System.Threading.Tasks.Task GecikmeMailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/ImportContact", ReplyAction="http://tempuri.org/ICrmService/ImportContactResponse")]
        System.Threading.Tasks.Task ImportContactAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/DogumGunuMailleri", ReplyAction="http://tempuri.org/ICrmService/DogumGunuMailleriResponse")]
        System.Threading.Tasks.Task DogumGunuMailleriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/TelefonKapat", ReplyAction="http://tempuri.org/ICrmService/TelefonKapatResponse")]
        System.Threading.Tasks.Task TelefonKapatAsync(string telid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GeriAranacakTelefonGorusmeleriOlustur", ReplyAction="http://tempuri.org/ICrmService/GeriAranacakTelefonGorusmeleriOlusturResponse")]
        System.Threading.Tasks.Task GeriAranacakTelefonGorusmeleriOlusturAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GeriAramaSaatAralikli9", ReplyAction="http://tempuri.org/ICrmService/GeriAramaSaatAralikli9Response")]
        System.Threading.Tasks.Task GeriAramaSaatAralikli9Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GeriAramaSaatAralikli12", ReplyAction="http://tempuri.org/ICrmService/GeriAramaSaatAralikli12Response")]
        System.Threading.Tasks.Task GeriAramaSaatAralikli12Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GeriAramaSaatAralikli15", ReplyAction="http://tempuri.org/ICrmService/GeriAramaSaatAralikli15Response")]
        System.Threading.Tasks.Task GeriAramaSaatAralikli15Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/Tekillestir", ReplyAction="http://tempuri.org/ICrmService/TekillestirResponse")]
        System.Threading.Tasks.Task TekillestirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/SMSRandevuBilgilendirme", ReplyAction="http://tempuri.org/ICrmService/SMSRandevuBilgilendirmeResponse")]
        System.Threading.Tasks.Task SMSRandevuBilgilendirmeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/Import_Tel", ReplyAction="http://tempuri.org/ICrmService/Import_TelResponse")]
        System.Threading.Tasks.Task Import_TelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/NetworkMailBilgilendirme", ReplyAction="http://tempuri.org/ICrmService/NetworkMailBilgilendirmeResponse")]
        System.Threading.Tasks.Task NetworkMailBilgilendirmeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/WebFormMailHatirlatma", ReplyAction="http://tempuri.org/ICrmService/WebFormMailHatirlatmaResponse")]
        System.Threading.Tasks.Task WebFormMailHatirlatmaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/Import_albaraka", ReplyAction="http://tempuri.org/ICrmService/Import_albarakaResponse")]
        System.Threading.Tasks.Task Import_albarakaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/NetworkSozlesmeHatirlatma", ReplyAction="http://tempuri.org/ICrmService/NetworkSozlesmeHatirlatmaResponse")]
        System.Threading.Tasks.Task NetworkSozlesmeHatirlatmaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/FirsatHatirlatma", ReplyAction="http://tempuri.org/ICrmService/FirsatHatirlatmaResponse")]
        System.Threading.Tasks.Task FirsatHatirlatmaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/NetworkHesaplama", ReplyAction="http://tempuri.org/ICrmService/NetworkHesaplamaResponse")]
        System.Threading.Tasks.Task NetworkHesaplamaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/OtoSenet", ReplyAction="http://tempuri.org/ICrmService/OtoSenetResponse")]
        System.Threading.Tasks.Task OtoSenetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/OtoOdeme", ReplyAction="http://tempuri.org/ICrmService/OtoOdemeResponse")]
        System.Threading.Tasks.Task OtoOdemeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/UpdateOrtaklar", ReplyAction="http://tempuri.org/ICrmService/UpdateOrtaklarResponse")]
        System.Threading.Tasks.Task UpdateOrtaklarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateOpportunity2", ReplyAction="http://tempuri.org/ICrmService/CreateOpportunity2Response")]
        System.Threading.Tasks.Task<string> CreateOpportunity2Async(WS.Opp opp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateReservation", ReplyAction="http://tempuri.org/ICrmService/CreateReservationResponse")]
        System.Threading.Tasks.Task<string> CreateReservationAsync(string emailaddress, string mobilephone, System.DateTime date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateOpportunityZingat", ReplyAction="http://tempuri.org/ICrmService/CreateOpportunityZingatResponse")]
        System.Threading.Tasks.Task<string> CreateOpportunityZingatAsync(WS.Opp opp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateOpportunity", ReplyAction="http://tempuri.org/ICrmService/CreateOpportunityResponse")]
        System.Threading.Tasks.Task<string> CreateOpportunityAsync(WS.Opp opp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateContactProject", ReplyAction="http://tempuri.org/ICrmService/CreateContactProjectResponse")]
        System.Threading.Tasks.Task<string> CreateContactProjectAsync(string contactId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/UpdateSenet", ReplyAction="http://tempuri.org/ICrmService/UpdateSenetResponse")]
        System.Threading.Tasks.Task<string> UpdateSenetAsync(string logosenetid, System.DateTime odenmetarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/SatisNumaralandirma", ReplyAction="http://tempuri.org/ICrmService/SatisNumaralandirmaResponse")]
        System.Threading.Tasks.Task<string> SatisNumaralandirmaAsync(string satisid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateCustomer", ReplyAction="http://tempuri.org/ICrmService/CreateCustomerResponse")]
        System.Threading.Tasks.Task CreateCustomerAsync(string ad, string soyad, string tel, string email, string tdata, string uyruk, string haberdar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateIncident", ReplyAction="http://tempuri.org/ICrmService/CreateIncidentResponse")]
        System.Threading.Tasks.Task<WS.SResult> CreateIncidentAsync(WS.Login login, WS.Incident inc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateCustomerNote", ReplyAction="http://tempuri.org/ICrmService/CreateCustomerNoteResponse")]
        System.Threading.Tasks.Task CreateCustomerNoteAsync(string guid, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/CreateIYS", ReplyAction="http://tempuri.org/ICrmService/CreateIYSResponse")]
        System.Threading.Tasks.Task<string> CreateIYSAsync(string username, string password, string recipient, string status, string type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICrmServiceChannel : WS.ICrmService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CrmServiceClient : System.ServiceModel.ClientBase<WS.ICrmService>, WS.ICrmService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrmServiceClient() : 
                base(CrmServiceClient.GetDefaultBinding(), CrmServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrmService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CrmServiceClient.GetBindingForEndpoint(endpointConfiguration), CrmServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrmServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrmServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task malsahibisilmeAsync()
        {
            return base.Channel.malsahibisilmeAsync();
        }
        
        public System.Threading.Tasks.Task VIPOnayMailAsync()
        {
            return base.Channel.VIPOnayMailAsync();
        }
        
        public System.Threading.Tasks.Task GecikmeMailAsync()
        {
            return base.Channel.GecikmeMailAsync();
        }
        
        public System.Threading.Tasks.Task ImportContactAsync()
        {
            return base.Channel.ImportContactAsync();
        }
        
        public System.Threading.Tasks.Task DogumGunuMailleriAsync()
        {
            return base.Channel.DogumGunuMailleriAsync();
        }
        
        public System.Threading.Tasks.Task TelefonKapatAsync(string telid)
        {
            return base.Channel.TelefonKapatAsync(telid);
        }
        
        public System.Threading.Tasks.Task GeriAranacakTelefonGorusmeleriOlusturAsync()
        {
            return base.Channel.GeriAranacakTelefonGorusmeleriOlusturAsync();
        }
        
        public System.Threading.Tasks.Task GeriAramaSaatAralikli9Async()
        {
            return base.Channel.GeriAramaSaatAralikli9Async();
        }
        
        public System.Threading.Tasks.Task GeriAramaSaatAralikli12Async()
        {
            return base.Channel.GeriAramaSaatAralikli12Async();
        }
        
        public System.Threading.Tasks.Task GeriAramaSaatAralikli15Async()
        {
            return base.Channel.GeriAramaSaatAralikli15Async();
        }
        
        public System.Threading.Tasks.Task TekillestirAsync()
        {
            return base.Channel.TekillestirAsync();
        }
        
        public System.Threading.Tasks.Task SMSRandevuBilgilendirmeAsync()
        {
            return base.Channel.SMSRandevuBilgilendirmeAsync();
        }
        
        public System.Threading.Tasks.Task Import_TelAsync()
        {
            return base.Channel.Import_TelAsync();
        }
        
        public System.Threading.Tasks.Task NetworkMailBilgilendirmeAsync()
        {
            return base.Channel.NetworkMailBilgilendirmeAsync();
        }
        
        public System.Threading.Tasks.Task WebFormMailHatirlatmaAsync()
        {
            return base.Channel.WebFormMailHatirlatmaAsync();
        }
        
        public System.Threading.Tasks.Task Import_albarakaAsync()
        {
            return base.Channel.Import_albarakaAsync();
        }
        
        public System.Threading.Tasks.Task NetworkSozlesmeHatirlatmaAsync()
        {
            return base.Channel.NetworkSozlesmeHatirlatmaAsync();
        }
        
        public System.Threading.Tasks.Task FirsatHatirlatmaAsync()
        {
            return base.Channel.FirsatHatirlatmaAsync();
        }
        
        public System.Threading.Tasks.Task NetworkHesaplamaAsync()
        {
            return base.Channel.NetworkHesaplamaAsync();
        }
        
        public System.Threading.Tasks.Task OtoSenetAsync()
        {
            return base.Channel.OtoSenetAsync();
        }
        
        public System.Threading.Tasks.Task OtoOdemeAsync()
        {
            return base.Channel.OtoOdemeAsync();
        }
        
        public System.Threading.Tasks.Task UpdateOrtaklarAsync()
        {
            return base.Channel.UpdateOrtaklarAsync();
        }
        
        public System.Threading.Tasks.Task<string> CreateOpportunity2Async(WS.Opp opp)
        {
            return base.Channel.CreateOpportunity2Async(opp);
        }
        
        public System.Threading.Tasks.Task<string> CreateReservationAsync(string emailaddress, string mobilephone, System.DateTime date, string time)
        {
            return base.Channel.CreateReservationAsync(emailaddress, mobilephone, date, time);
        }
        
        public System.Threading.Tasks.Task<string> CreateOpportunityZingatAsync(WS.Opp opp)
        {
            return base.Channel.CreateOpportunityZingatAsync(opp);
        }
        
        public System.Threading.Tasks.Task<string> CreateOpportunityAsync(WS.Opp opp)
        {
            return base.Channel.CreateOpportunityAsync(opp);
        }
        
        public System.Threading.Tasks.Task<string> CreateContactProjectAsync(string contactId, string projectId)
        {
            return base.Channel.CreateContactProjectAsync(contactId, projectId);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSenetAsync(string logosenetid, System.DateTime odenmetarihi)
        {
            return base.Channel.UpdateSenetAsync(logosenetid, odenmetarihi);
        }
        
        public System.Threading.Tasks.Task<string> SatisNumaralandirmaAsync(string satisid)
        {
            return base.Channel.SatisNumaralandirmaAsync(satisid);
        }
        
        public System.Threading.Tasks.Task CreateCustomerAsync(string ad, string soyad, string tel, string email, string tdata, string uyruk, string haberdar)
        {
            return base.Channel.CreateCustomerAsync(ad, soyad, tel, email, tdata, uyruk, haberdar);
        }
        
        public System.Threading.Tasks.Task<WS.SResult> CreateIncidentAsync(WS.Login login, WS.Incident inc)
        {
            return base.Channel.CreateIncidentAsync(login, inc);
        }
        
        public System.Threading.Tasks.Task CreateCustomerNoteAsync(string guid, string note)
        {
            return base.Channel.CreateCustomerNoteAsync(guid, note);
        }
        
        public System.Threading.Tasks.Task<string> CreateIYSAsync(string username, string password, string recipient, string status, string type)
        {
            return base.Channel.CreateIYSAsync(username, password, recipient, status, type);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmService))
            {
                return new System.ServiceModel.EndpointAddress("http://212.156.40.34:8082/CrmService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrmServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrmService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrmServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrmService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrmService,
        }
    }
}
